export const styles = {
  tabsContainer: {
    display: "flex",
    borderBottom: "2px solid #ccc",
    backgroundColor: "#F3F1ED",
    width: "100%",
    borderRadius: 10,
    overflow: "hidden",
    height: 40,
  },

  buttonWrapper: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "flex-end",
    marginTop: 5,
  },
  activeButton: {
    padding: "10px 20px",
    border: "none",
    cursor: "pointer",
    background: "none",
    outline: "none",
    width: "33%",
    fontFamily: "Montserrat",
  },
  inputBox: {
    padding: "10px",
    width: "95%",
    //     maxWidth: "400px",
    border: "1px solid #ccc",
    borderRadius: "4px",
    fontSize: "14px",
    marginTop: "10px",
    fontFamily: "Montserrat",
  },
  addButton: {
    padding: "10px",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    boxShadow: "0 2px 5px rgba(0,0,0,0.15)",
    transition: "background-color 0.3s ease",
    alignSelf: "flex-end",
  },
  groupWrapper: {
    padding: " 0px 10px",
    borderBottom: "1px solid #ccc",
    borderRadius: "6px",
    marginBottom: "5px",
    // backgroundColor: "#f9f9f9",
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
  },
  backButton: {
    cursor: "pointer",
    color: "#25D366",
    marginBottom: "1rem",
    fontWeight: "bold",
    textAlign: "left",
    fontFamily: "Montserrat",
    // background:"#25D366"
  },
  deleteButton: {
    padding: "10px",
    backgroundColor: "#dc3545",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    cursor: "pointer",
    boxShadow: "0 2px 5px rgba(0,0,0,0.15)",
    transition: "background-color 0.3s ease",
  },
  addNumberButton: {
    padding: "10px 20px",
    background: "#25D366",
    color: "#ffffff",
    border: "none",
    borderRadius: "8px",
    cursor: "pointer",
    fontSize: "14px",
    boxShadow: "0 4px 10px rgba(0, 0, 0, 0.2)",
    transition: "all 0.3s ease",
    fontFamily: "Montserrat",
  },
};
